name: Lint fish scripts

on:
  push:
    branches:
      - master
      - releases/**
    paths:
      - ".github/workflows/lint-fish.yml"
      - "**.fish"
  pull_request:
    branches:
      - master
      - releases/**
    paths:
      - ".github/workflows/lint-fish.yml"
      - "**.fish"

defaults:
  run:
    shell: fish {0}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install fish
        uses: fish-actions/install-fish@d6d9d26231a15f8d9a6b3e74b3db45512440e3e8 # renovate: tag=v1.1.0

      - name: Checkout branch
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3

      - name: Lint fish scripts
        run: source .github/scripts/lint-fish.fish
