name: Validate renovate config

on:
  push:
    branches:
      - master
      - releases/**
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"
  pull_request:
    branches:
      - master
      - releases/**
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"

jobs:
  validate-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2

      - name: Validate renovate config
        run: npx -y --package renovate -- renovate-config-validator
